import { useState, type FormEvent } from 'react'
import { Navigate } from 'react-router-dom'
import { useAuth } from '../auth'
import { homeFor } from '../auth-policy'
import LogoMark from '../components/LogoMark'
import { Button } from '../admin/ui'
export default function LoginPage() {
  const { session, login, register } = useAuth()
  const [registration, setRegistration] = useState(false), [name, setName] = useState(''), [email, setEmail] = useState(''), [password, setPassword] = useState(''), [show, setShow] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState('')
  if (session) return <Navigate to={homeFor(session.role)} replace />
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); try { if (registration) await register(name, email, password); else await login(email, password) } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }
  const input = 'mt-2 w-full rounded-lg border border-line bg-bg px-4 py-3 text-sm focus:outline-2 focus:outline-accent'
  return <main className="min-h-dvh bg-bg lg:grid lg:grid-cols-2"><section className="bg-sidebar border-b lg:border-r border-line px-6 py-8 lg:p-16 flex flex-col justify-between"><a href="/login" className="inline-flex items-center gap-3 text-2xl font-semibold"><LogoMark size={30} />LuậtGT</a><div className="hidden lg:block max-w-lg py-20"><h1 className="text-5xl font-semibold leading-tight">An tâm trên<br />mọi hành trình.</h1><p className="mt-6 text-sm leading-7 text-text-secondary">Tra cứu luật giao thông, tìm hiểu biển báo và ôn thi giấy phép lái xe.</p></div><p className="hidden lg:block text-xs text-muted">Trợ lý luật giao thông & ôn thi lái xe</p></section><section className="flex items-center justify-center px-6 py-12"><div className="w-full max-w-[400px]"><h2 className="text-3xl font-semibold">{registration ? 'Tạo tài khoản' : 'Đăng nhập LuậtGT'}</h2><form onSubmit={submit} className="mt-8 space-y-5">{registration && <label className="block text-sm">Họ tên<input autoComplete="name" required maxLength={100} value={name} onChange={e => setName(e.target.value)} className={input} /></label>}<label className="block text-sm">Email<input type="email" autoComplete="username" required maxLength={254} value={email} onChange={e => setEmail(e.target.value)} className={input} /></label><label className="block text-sm">Mật khẩu<input type={show ? 'text' : 'password'} autoComplete={registration ? 'new-password' : 'current-password'} required minLength={registration ? 12 : undefined} maxLength={72} value={password} onChange={e => setPassword(e.target.value)} className={input} /></label><button type="button" className="min-h-8 text-xs underline underline-offset-4" aria-pressed={show} onClick={() => setShow(v => !v)}>{show ? 'Ẩn mật khẩu' : 'Hiện mật khẩu'}</button>{registration && <p className="text-xs text-muted">Mật khẩu từ 12 ký tự, tối đa 72 byte. Tài khoản mới dành cho người học.</p>}{error && <p role="alert" className="text-sm text-red-700">{error}</p>}<Button type="submit" variant="dark" className="w-full" disabled={busy}>{busy ? 'Đang xử lý…' : registration ? 'Tạo tài khoản' : 'Đăng nhập'}</Button></form><button type="button" className="mt-6 min-h-10 text-sm underline underline-offset-4" onClick={() => { setRegistration(v => !v); setError('') }}>{registration ? 'Đã có tài khoản? Đăng nhập' : 'Chưa có tài khoản? Đăng ký'}</button></div></section></main>
}
