param(
    [Parameter(Mandatory=$true)][string]$EnvFile,
    [string]$ComposeFile = (Join-Path (Split-Path -Parent $PSScriptRoot) 'docker-compose.step8.kag.yml')
)
$ErrorActionPreference = 'Stop'
$taskRoot = [IO.Path]::GetFullPath((Split-Path -Parent $PSScriptRoot))
$taskEnvPath = [IO.Path]::GetFullPath($EnvFile)
$taskEnv = @{}
foreach ($taskLine in [IO.File]::ReadAllLines($taskEnvPath)) {
    if (!$taskLine.Trim() -or $taskLine.TrimStart().StartsWith('#')) { continue }
    if ($taskLine -notmatch "^([A-Z][A-Z0-9_]*)='([^']*)'$" -or $taskEnv.ContainsKey($Matches[1])) { throw 'Use a nonduplicate Step8 dotenv generated by init-step8-env.ps1.' }
    $taskEnv[$Matches[1]] = $Matches[2]
}
$taskProject = $taskEnv['STEP8_KAG_PROJECT']
if ($taskProject -notmatch '^kag-s8-[a-z0-9][a-z0-9-]*$') { throw 'Independent kag-s8 project required.' }
$taskJson = & rtk proxy docker compose --project-directory $taskRoot --env-file $taskEnvPath -f $ComposeFile config --format json 2>&1
if ($LASTEXITCODE) { throw 'Compose configuration invalid; values suppressed to protect credentials.' }
$taskConfig = ($taskJson -join "`n") | ConvertFrom-Json
if ($taskConfig.name -ne $taskProject) { throw 'Project override or identity mismatch.' }
$taskServices = @('openspg-mysql','openspg-neo4j','openspg-minio','openspg-server','kag-api')
if (Compare-Object @($taskConfig.services.PSObject.Properties.Name) $taskServices) { throw 'Exactly five KAG services required.' }
$taskVolumeNames = @('openspg-mysql-data','openspg-neo4j-data','openspg-neo4j-logs','openspg-minio-data')
if (Compare-Object @($taskConfig.volumes.PSObject.Properties.Name) $taskVolumeNames) { throw 'Unexpected storage scope.' }
foreach ($taskName in $taskVolumeNames) {
    $taskVolume = $taskConfig.volumes.$taskName
    if ($taskVolume.name -ne "${taskProject}_$taskName" -or $taskVolume.external -or $taskVolume.driver_opts) { throw 'Volume must be independent project-owned storage.' }
}
if (@($taskConfig.networks.PSObject.Properties.Name).Count -ne 1 -or !$taskConfig.networks.private.internal -or $taskConfig.networks.private.external -or $taskConfig.networks.private.name -ne "${taskProject}_private") { throw 'Step8 private internal network required; no historical/shared network.' }
$taskPorts = @{}
$taskMemory = @{'openspg-mysql'=402653184;'openspg-neo4j'=2147483648;'openspg-minio'=268435456;'openspg-server'=1610612736;'kag-api'=1073741824}
$taskPinnedImages = @{
    'openspg-mysql'='spg-registry.us-west-1.cr.aliyuncs.com/spg/openspg-mysql@sha256:71eb546d5fc5faf70b3d8a358c022f601591b54a029b79298f2fa0302e46de9a'
    'openspg-neo4j'='spg-registry.us-west-1.cr.aliyuncs.com/spg/openspg-neo4j@sha256:4bc5b7f6b83d333b1d2c8f60ac145c068d77d50bca65b3a07c927f9e2a541eb9'
    'openspg-server'='spg-registry.us-west-1.cr.aliyuncs.com/spg/openspg-server@sha256:fe6708deef9ebb8da8da7b1cb643e83b827769a5be8811961311639aa1f2cb88'
}
$taskDataMounts = @{'openspg-mysql'=@('openspg-mysql-data:/var/lib/mysql');'openspg-neo4j'=@('openspg-neo4j-data:/data','openspg-neo4j-logs:/logs');'openspg-minio'=@('openspg-minio-data:/data');'openspg-server'=@()}
foreach ($taskService in $taskConfig.services.PSObject.Properties) {
    $taskValue = $taskService.Value
    if ($taskPinnedImages.ContainsKey($taskService.Name) -and $taskValue.image -ne $taskPinnedImages[$taskService.Name]) { throw 'Pinned OpenSPG image declaration changed.' }
    if ($taskService.Name -eq 'openspg-minio' -and ($taskValue.image -ne $taskEnv['STEP8_MINIO_IMAGE'] -or $taskEnv['STEP8_MINIO_IMAGE_ID'] -ne 'sha256:5e65d87b41ed46cbdb6edcd5f0bc92ab947f0f9873d609b41e2c071f6028f532')) { throw 'Retained MinIO declaration mismatch; actual cache needs build/deploy preflight.' }
    if ($taskValue.container_name -or $taskValue.profiles -or $taskValue.privileged -or $taskValue.network_mode -or $taskValue.pid -or $taskValue.ipc -or $taskValue.links -or $taskValue.volumes_from -or $taskValue.extra_hosts -or $taskValue.devices) { throw 'Unsafe or unexpected service coupling.' }
    if ($taskValue.platform -ne 'linux/amd64' -or $taskValue.pull_policy -ne 'never' -or $taskValue.restart -ne 'no') { throw 'No automatic pull/restart; canonical platform required.' }
    if ([int64]$taskValue.mem_limit -ne $taskMemory[$taskService.Name] -or [double]$taskValue.cpus -le 0 -or [double]$taskValue.cpus -gt 1 -or $taskValue.pids_limit -le 0) { throw 'Bounded candidate resource caps required; these are not capacity proof.' }
    if (@($taskValue.networks.PSObject.Properties.Name).Count -ne 1 -or @($taskValue.networks.PSObject.Properties.Name)[0] -ne 'private') { throw 'Only private KAG network allowed.' }
    foreach ($taskDependency in $taskValue.depends_on.PSObject.Properties.Name) {
        if ($taskDependency -notin $taskServices) { throw 'Cross-stack dependency denied.' }
    }
    foreach ($taskPort in $taskValue.ports) {
        if ($taskService.Name -notin @('kag-api','openspg-server') -or $taskPort.host_ip -ne '127.0.0.1' -or $taskPorts.ContainsKey([string]$taskPort.published)) { throw 'Unexpected, public or duplicate published port.' }
        $taskPorts[[string]$taskPort.published] = $true
    }
    foreach ($taskMount in $taskValue.volumes) {
        if ($taskService.Name -ne 'kag-api' -and ($taskMount.type -ne 'volume' -or $taskMount.source -notin $taskVolumeNames)) { throw 'Data services cannot bind host/legacy storage.' }
    }
    if ($taskService.Name -ne 'kag-api') {
        $taskActual = @(foreach ($taskMount in $taskValue.volumes) { "$($taskMount.source):$($taskMount.target)" })
        if ($taskActual.Count -ne $taskDataMounts[$taskService.Name].Count -or ($taskActual.Count -and (Compare-Object $taskActual $taskDataMounts[$taskService.Name]))) { throw 'Data volume destination/service binding mismatch.' }
    }
}
$taskApi = $taskConfig.services.'kag-api'
foreach ($taskService in @('kag-api','openspg-server')) {
    $taskPort = @($taskConfig.services.$taskService.ports)
    $taskTarget = if ($taskService -eq 'kag-api') { 8000 } else { 8887 }
    $taskKey = if ($taskService -eq 'kag-api') { 'STEP8_API_PORT' } else { 'STEP8_OPENSPG_PORT' }
    if ($taskPort.Count -ne 1 -or $taskPort[0].target -ne $taskTarget -or [string]$taskPort[0].published -ne $taskEnv[$taskKey] -or $taskPort[0].protocol -ne 'tcp') { throw 'Exact localhost API/OpenSPG port mapping required.' }
}
if (!$taskApi.read_only -or 'ALL' -notin $taskApi.cap_drop -or 'no-new-privileges:true' -notin $taskApi.security_opt -or $taskApi.user -notmatch '^[1-9][0-9]*:[1-9][0-9]*$' -or !$taskApi.init) { throw 'API requires non-root, read-only filesystem and dropped capabilities.' }
if ($taskApi.environment.KAG_OPERATIONAL_PROOF -ne 'DENY' -or $taskApi.environment.KAG_PRODUCTION_WRITE -ne 'BLOCKED' -or $taskApi.environment.KAG_PROVIDER_EGRESS -ne 'DENY' -or $taskApi.environment.KAG_HTTP_WORKERS -ne '1' -or $taskApi.environment.KAG_DEBUG_DUMP_CONFIG -ne '0') { throw 'Serving authority must remain denied.' }
if ($taskApi.environment.KAG_PROJECT_ID -or $taskApi.environment.KAG_PROJECT_HOST_ADDR) { throw 'Remote bootstrap configuration denied.' }
if ($taskApi.command -or $taskApi.entrypoint -or $taskApi.build.network -ne 'none' -or $taskApi.build.pull) { throw 'Entrypoint override or online build denied.' }
if ($taskApi.build.context -ne $taskRoot -or $taskApi.build.dockerfile -ne 'docker/kag-api/Dockerfile') { throw 'API must package existing pinned source.' }
if (Compare-Object @($taskApi.build.additional_contexts.PSObject.Properties.Name) @('http_wheels','vendor_objects')) { throw 'Exactly offline wheels and vendor objects build contexts required.' }
foreach ($taskContext in @('http_wheels','vendor_objects')) {
    $taskKey = if ($taskContext -eq 'http_wheels') { 'STEP8_HTTP_WHEELS_DIR' } else { 'STEP8_VENDOR_OBJECTS_DIR' }
    if ($taskApi.build.additional_contexts.$taskContext.Replace('\','/') -ne $taskEnv[$taskKey]) { throw 'Offline build context source override denied.' }
}
if ($taskApi.image -ne "${taskProject}-api:source") { throw 'API image must use a distinct Step8 identity.' }
if ($taskApi.build.args.KAG_RUNTIME_IMAGE -ne $taskEnv['STEP8_RUNTIME_IMAGE'] -or $taskEnv['STEP8_RUNTIME_IMAGE_ID'] -ne 'sha256:25190ba8f51e8d158db0910858e9de3de1e1324d29d8b236d4d120268fa7bf33') { throw 'Canonical base declaration mismatch; actual cache identity needs build preflight.' }
if (@($taskApi.volumes).Count -ne 2) { throw 'Exactly release and API-only credential binds required.' }
foreach ($taskMount in $taskApi.volumes) {
    if ($taskMount.type -ne 'bind' -or !$taskMount.read_only -or $taskMount.bind.create_host_path -or $taskMount.target -notin @('/release','/run/api-credentials')) { throw 'Unexpected writable/host-control API mount.' }
    $taskKey = if ($taskMount.target -eq '/release') { 'STEP8_RELEASE_DIR' } else { 'STEP8_API_CREDENTIALS_DIR' }
    if ($taskMount.source.Replace('\','/') -ne $taskEnv[$taskKey]) { throw 'API bind source override denied.' }
}
foreach ($taskScope in @('query','inspect')) {
    $taskName = "${taskScope}_token"
    $taskKey = "STEP8_$($taskScope.ToUpperInvariant())_SECRET_FILE"
    if (!$taskConfig.secrets.$taskName -or !$taskConfig.secrets.$taskName.file) { throw 'Exact bearer secret source/target binding required.' }
    if ($taskConfig.secrets.$taskName.file.Replace('\','/') -ne $taskEnv[$taskKey]) { throw 'Secret source override denied.' }
    if ($taskApi.environment."KAG_HTTP_$($taskScope.ToUpperInvariant())_SECRET_FILE" -ne "/run/secrets/$taskName") { throw 'H1 bearer secret file mapping required.' }
    $taskSecret = @($taskApi.secrets | Where-Object { $_.source -eq $taskName -and $_.target -eq "/run/secrets/$taskName" })
    if ($taskSecret.Count -ne 1) { throw 'Exact bearer secret source/target binding required.' }
}
if (@($taskApi.secrets).Count -ne 2) { throw 'Only two bearer secrets may be mounted.' }
foreach ($taskName in @('STEP8_MYSQL_PASSWORD','STEP8_NEO4J_PASSWORD','STEP8_MINIO_PASSWORD')) {
    if ($taskEnv[$taskName] -notmatch '^[a-f0-9]{64}$') { throw 'Independent random credentials required.' }
}
if ($taskConfig.services.'openspg-mysql'.environment.MYSQL_ROOT_PASSWORD -ne $taskEnv['STEP8_MYSQL_PASSWORD'] -or $taskConfig.services.'openspg-neo4j'.environment.NEO4J_AUTH -ne "neo4j/$($taskEnv['STEP8_NEO4J_PASSWORD'])" -or $taskConfig.services.'openspg-minio'.environment.MINIO_ROOT_PASSWORD -ne $taskEnv['STEP8_MINIO_PASSWORD']) { throw 'Process environment overrides independent credentials.' }
Write-Output 'PASS_STATIC_CONFIG: five services, independent resources, localhost ports, offline build declaration, auth mounts and DENY policy. No deployment/capacity/image-compatibility proof.'
